import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { Geist, Geist_Mono, Sora } from "next/font/google";
import { routing } from "@/i18n/routing";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import {LocaleHtmlSync} from "@/components/LocaleHtmlSync";
import { ThemeHtmlSync } from "@/components/ThemeHtmlSync";
import { PageTransition } from "@/components/layout/PageTransition";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} ${sora.variable} flex flex-col flex-1 antialiased`}
    >
      <LocaleHtmlSync locale={locale} />
      <ThemeHtmlSync />
      <NextIntlClientProvider messages={messages}>
        <Header />
        <PageTransition>{children}</PageTransition>
        <Footer />
      </NextIntlClientProvider>
    </div>
  );
}
